services:
- redis
- postgresql
- docker
language: python
jobs:
  include:
  - python: '3.7'
    env: TOX_ENV=py37-sentry20
install:
- sudo apt update
- sudo apt install libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config -y
- docker network create -d bridge sentry_test
- docker run -p 8123:8123 -p 9000:9000 -p 9009:9009 --network sentry_test -d --name
  sentry_clickhouse yandex/clickhouse-server:20.3.9.70
- docker run -p 1218:1218 -d -e SNUBA_SETTINGS=docker -e DEBUG=1 -e CLICKHOUSE_HOST=sentry_clickhouse
  --network sentry_test --name sentry_snuba getsentry/snuba:nightly devserver --no-workers
- docker ps -a
- travis_retry pip install tox
before_script:
- psql -c 'create database sentry;' -U postgres
script: tox -e $TOX_ENV
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "QjOvFuYM/7VOlysxl0I2FX/i/tOD66kg/PVKc/W5Pqc+TTOew439XoiyBwyA6k1nNml9Dd2vf/DvNjlET5HfXOoEiehoIPuKDYLmsxSRoOyue855o1OT7fTTPBQ7S/+oaAUf1vSHIqh1RUh5gm6Zhcuiz+sTV3dWIoFdAVuN7bWqqtThEIvxZ5Ug2n88DTPLMkxR9wlrwG1DHm62/JYwF51GqyRc4DS8kPTn6QTIaW2NmkIY+TXFNxXKah2TkeWn+mb//RJBb/KckgQj7zOtE8oB6MtJkseLgjNn2DBL4qRbFbJRstqF7i2iKkE0JvCravci79YElsu89dwQ80tfLEVs1o84bQTm67e7mQW7EVaX2mG7SX6RKS/YCChp3ZFpV5cdsevSNpANdKnFPqZURt3oNXdzs6WAhUkVtOIhIxHka61kYPqwBlTzyRtmxXOrjC4LbjPld8KgWffthmo2Kwnj8q0IXevBlMbI2xsHyDxI753r7Vo9Z90r3XNtBCWHlz6mdZfXW2t9cSGU+8GjcIlqi9J769/1Hf1YQFsfK/hZwu8cRqk0SQuyTVfnUReHWd6PCVXW/wkwsDCPmu8scK42mjvWw4BdXxKn4GGYFhizT72XvnsMyyJLT5ZG1QftrwGC3hOGoyX3tUxvPCjjGQZ2iXtKjGqJT2fw+GOGdv8="
  skip_existing: true
  on:
    tags: true
  distributions: sdist bdist_wheel
